[bilibili_ytdl]
profile-desc=blibili-bangumi-ytdl
# profile-cond=path:match("bilibili.com/bangumi")~=nil
profile-cond=(path:match("https?://[^/]*bilibili%.com/bangumi")~=nil) or (path:match("https?://live%.bilibili%.com")~=nil)
profile-restore=copy
ytdl-raw-options=cookies-from-browser=firefox
ytdl-format=bestvideo[height<=?2160][width<=?3840][vcodec!=?av01]+bestaudio/best


[anime_shaders]
profile-desc=anime shaders
profile-cond=path:match("Anime")~=nil
profile-restore=copy
# Anime4K: Mode A+A (HQ)
# Windows
# glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_VL.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl;~~/shaders/Anime4K_Restore_CNN_M.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
# Linux
# glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"

# Anime4K: Mode C+A (HQ)
# Linux
# glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"

# AMD FSR RT
# INFO: need vo=gpu-next
# glsl-shaders="~~/shaders/AMD_FSR_EASU_chroma_RT.glsl:~~/shaders/AMD_FSR_EASU_luma_RT.glsl:~~/shaders/AMD_FSR_RCAS_luma_RT.glsl:~~/shaders/AMD_FSR_RT.glsl"
# glsl-shaders="~~/shaders/AMD_FSR_EASU_chroma_RT.glsl:~~/shaders/AMD_FSR_EASU_rgb_RT.glsl:~~/shaders/AMD_FSR_RCAS_rgb_RT.glsl:~~/shaders/AMD_FSR_rgb_RT.glsl"
